### ISSUE TITLE
Thaddius

### ISSUE THREAD

**Issue by Kelzior** [scriptdev2/scriptdev2-classic#38]
fixed.

**Comment by cala** [comment]
In Classic (and TBC), Thaddius was untargetable for a while after defeating the two mini-boss, leaving time for the players to position themselves. After this "disable" time, he then "awaked" and engaged combat while being rooted (unable to walk).

I think the DB part should be (almost) correct, I remember fixing the flags in Classic DB 1.2.
I need to look at it and what exactly the script does.

**Comment by xfurry** [comment]
Flags are also set in the script.
Just make sure that you have the right spawns for https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/eastern_kingdoms/naxxramas/naxxramas.h#L70

**Comment by Kelzior** [comment]
@cala I tried this again and did wait for like 15 mins to test the "disable" time and nothing happened..
