### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Kelzior** [scriptdev2/scriptdev2-classic#39]
Update: Please note that Ragnaros is summoned: https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/eastern_kingdoms/molten_core/boss_majordomo_executus.cpp#L299
and will only become attackable after intro is complete: https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/eastern_kingdoms/molten_core/boss_ragnaros.cpp#L186 , Xfurry

**Comment by cala** [comment]
Sounds like wrong flags. Probably DB side. I'll look at this.

**Comment by xfurry** [comment]
Please note that Ragnaros is summoned: https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/eastern_kingdoms/molten_core/boss_majordomo_executus.cpp#L299
and will only become attackable after intro is complete: https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/eastern_kingdoms/molten_core/boss_ragnaros.cpp#L186
