### ISSUE TITLE
[AQ40][Ouro]

### ISSUE THREAD

**Issue by Kelzior** [scriptdev2/scriptdev2-classic#41]
Well as per the script Ouro should be summoned: https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/kalimdor/temple_of_ahnqiraj/boss_ouro.cpp#L269

xfurry

**Comment by cala** [comment]
Size = most likely DB stuff.
Not aggroing : I need to look at this, there may be several reasons.

**Comment by xfurry** [comment]
> Not aggroing : I need to look at this, there may be several reasons.

Well as per the script Ouro should be summoned: https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/kalimdor/temple_of_ahnqiraj/boss_ouro.cpp#L269
So probably you are missing the trigger, but instead you have the boss.
It would be good to check with UDB.
