### ISSUE TITLE
Noth the Plaguebringer 

### ISSUE THREAD

**Issue by Kelzior** [scriptdev2/scriptdev2-classic#42]
Noth the Plaguebringer resets on balcony

**Comment by xfurry** [comment]
I'm not sure about classic, but on master it certainly doesn't happen.
Please check with @cala or @Tobschinski .

**Comment by Tobschinski** [comment]
Nope, Noth does not evade on my end. I see some missing spells and flags, but none of them are related to the described issue.

**Comment by Kelzior** [comment]
Does not happen everytime
