### ISSUE TITLE
Boss: Ouro not spawning

### ISSUE THREAD

**Issue by Kelzior** [scriptdev2/scriptdev2-classic#46]
Lastest core and the boss is not spawning for sure.

**Comment by xfurry** [comment]
> Lastest core and the boss is not spawning for sure.

Was this an issue before?
I suspect that this might be a DB problem. Poke @cala to check if all the triggers for Ouro are in place.

**Comment by cala** [comment]
I investigated it and the NPC 15957 (Ouro Spawner) is at the same place that in UDB. Flags are slightly different. I'll dig this.

**Comment by Tobschinski** [comment]
The spell that is used to summon Ouro is 26061.

But the Ouro Spawner uses the parent spell 26642 which will trigger spell 26061 after 30 seconds. That's the reason why Ouro will not spawn right away.

(The parent spell should only be used by later summoned dirt mounds, because the submerge phase lasts 30 seconds.)

**Comment by xfurry** [comment]
The solution isn't good, nor right.
I checked the npc and it looks the same as in UDB. The spell should behave the same: https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/kalimdor/temple_of_ahnqiraj/boss_ouro.cpp#L270 
The trigger doesn't get in combat with anybody (or shouldn't), so there is no reason for it to evade.
So unless there is some creature linking implemented, everything should work fine.

I have to setup a classic core to see why is the boss behaving like this.

**Comment by Tobschinski** [comment]
ServerToClient: SMSG_AI_REACTION (0x06AF) Length: 12 ConnIdx: 3 EP:  Time: 09.27.2014 13:33:57.888 Number: 106540
Reaction: Hostile (2)
Guid: Full: 0xF1303E5500017EC9 Type: Unit Entry: 15957 Low: 97993

**Comment by xfurry** [comment]
Any clue why is this happening?

**Comment by Tobschinski** [comment]
Why does the spell behave the same? 

Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 1, misc = 0 (0), periodic = 30000
Trigger spell: 26061 - Summon Ouro. Chance = 101

**Comment by xfurry** [comment]
The idea is that there are 30 sec of animation before the boss spawn.
The trigger should't get in combat with anybody. If this happens, we need to understand why.

**Comment by Tobschinski** [comment]
Okay, I totally understand one has to find the cause for this, but that aside, this isn't the correct summoning process.
The SMSG posted above is from retail, not mangos. The spawner will and should get in combat with you. And there is no intro, Ouro will be up at once.

-----

Apart from that, will the quake 26093 that is constantly cast put the spawner in combat if it hits someone, no matter what flags you chose?

**Comment by xfurry** [comment]
If the SMSG is from retail, then it seems that we are doing things wrong.
It would be nice if you can send me the sniff file in private, so that I can check it and fix the encounter.

**Comment by Tobschinski** [comment]
Yo, meet me on IRC whenever you have the time.

**Comment by Kelzior** [comment]
bumpppppppppppppp

**Comment by xfurry** [comment]
Relax....
This is WIP on my side. Will fix asap.

**Comment by Kelzior** [comment]
Any news on this? regards

**Comment by Kelzior** [comment]
?
