### ISSUE TITLE
Boss: Cthun

### ISSUE THREAD

**Issue by Kelzior** [scriptdev2/scriptdev2-classic#47]
SDName: Boss_Cthun
SDComment: Transform spell has some minor core issues. Eject from stomach event contains workarounds because of the missing spells. Digestive Acid should be handled in core.

*You don't get teleported to the stomach (Digstive Acid keeps stacking up cuz it thinks ur in the stomach)

C'thun: It all works properly except p3 when he's supposed to digest us to weaken him. What happens is actually really weird. We don't get thrown into his stomach, but we get the debuffs. Which makes it impossible to stop the stacks from stacking up, which would happen when we leave his stomach.*

**Comment by Schmoozerd** [comment]
SPELL_DIGESTIVE_ACID_TELEPORT = 26220, // stomach teleport spell
The spell might require proper coordinates within the DB, not sure here

**Comment by Kelzior** [comment]
Fixed
