### ISSUE TITLE
Kel'thuzad 

### ISSUE THREAD

**Issue by Kelzior** [scriptdev2/scriptdev2-classic#48]
Instance: Naxxramas
NPC ID: 15990
Bug: Kelthuzad's The shadow fissure spell animation does not work.
What should happen: The Shadow fissure spell should work, wich is the "Red circle animation"
spell id: 27810 (http://db.vanillagaming.org/?spell=27810)

**Comment by xfurry** [comment]
This looks like an acid-classic issue.
Please check the script for creature 16129 on Acid-wotlk and copy the logic from that version. I think that @Tobschinski can submit a fix for acid-classic to fix this.
