### ISSUE TITLE
/

### ISSUE THREAD

**Issue by Kelzior** [scriptdev2/scriptdev2-classic#50]
/

**Comment by Kelzior** [comment]
@xfurry the script only starts when you attack the boss (with a gm char)

**Comment by Kelzior** [comment]
once you attack the boss with a gm command .damage 1   , it triggers.
@xfurry

**Comment by xfurry** [comment]
I have no idea.
I know that on 3.x works fine, so I tend to suspect that this is a DB issue.
Poke @cala  and @Tobschinski

**Comment by ghost** [comment]
my server also works well. @Kelzior  Are you ash?

**Comment by ghost** [comment]
i use the cmangos and scriptdev2-class. it works well

**Comment by Tobschinski** [comment]
I don't have any problems either.

**Comment by cala** [comment]
I never encountered this issue.

**Comment by Kelzior** [comment]
the second time I try, (after a wipe) it works good. not the first time
